Bindings for TestU01
LesBoloss-es/ocaml-rng-experiments pull request #3
Opened 2020-04-26 09:32 UTC by Niols

- assumes testu01 is installed on the system
- not *per se* to be merged, more like a base for discussion
- still includes a foreign build for TestU01. however, I didn't manage to use it to build the bindings
- I haven't found how to use types defined in C in OCaml, hence the fact that we're binding several functions at the same time, any idea?

2020-04-26 16:11 UTC, Kerl13 commented on c/testu01/stubs.c
> +}
According to TestU01's short guide page 15:

>  If the generator delivers less than 32 bits of resolution, then these bits must be left shifted so that the most significant bit is bit 31 (counting from 0)

Assuming that we want to keep OCaml's Random module interface we should add a left shift here I think

2020-04-26 16:11 UTC, Kerl13 commented on c/testu01/stubs.c
> +}
Adding ` << 2` indeed makes `Stdlib.Random.bits` pass `SmallCrush`

2020-04-26 16:11 UTC, Kerl13 commented on c/testu01/stubs.c
> +value caml_bbattery_SmallCrush(value name, value bits_closure) {
Should the `CAMLparam` and `CAMLreturn` macros be used here?
Section 20.5.1 suggests we do this but I don't quite understand what's happening under the hood to be honest

2020-04-26 16:11 UTC, Kerl13 commented on c/testu01/stubs.c
> +}
An alternative solution would be:
```C
unsigned int x = Int_val(caml_callback(*caml_bits_closure, Val_unit)):
unsigned int y = Int_val(caml_callback(*caml_bits_closure, Val_unit));
return (x << 2) | (y & 3);
```
to return 32 bits of data

2020-04-26 16:11 UTC, Kerl13 commented on c/testu01/stubs.c
> +value * caml_bits_closure = NULL;
W.r.t. our conversation on Signal: I see no better solution… I guess this is fine since Testu01 has the same limitation

2020-04-26 16:11 UTC, Kerl13 commented on c/testu01/stubs.c
> +}
Actually, maybe `x | ((y & 3) << 2)` is better since it mimics the behaviour of `Random.int64 0x100000000`

2020-04-26 16:28 UTC, Kerl13 commented on c/testu01/stubs.c
> +value caml_bbattery_SmallCrush(value name, value bits_closure) {
Related to this: you never use `CAMLprim`. It is not clear to me what it exactly does and whether it is mandatory. Maybe @VLanvin will have more insight about this?

2020-04-26 18:05 UTC, VLanvin commented on c/testu01/stubs.c
> +value caml_bbattery_SmallCrush(value name, value bits_closure) {
> Should the `CAMLparam` and `CAMLreturn` macros be used here?
> Section 20.5.1 suggests we do this but I don't quite understand what's happening under the hood to be honest

The macro ` CAMLparam`  should definitely be used, since the parameters are not expected to be immediate values. And even then, I'd advise against omitting it since the overhead is minimal and it can prevent long debugging sessions.
I'm not sure if `CAMLreturn` is necessary when returning `Val_unit` but I'd still add it for the same reasons.

> Related to this: you never use `CAMLprim`. It is not clear to me what it exactly does and whether it is mandatory. Maybe @VLanvin will have more insight about this?

As far as I know, `CAMLprim` is an old macro that is only there for compatibility purposes and can/should be omitted (actually, I think its definition is empty now).

2020-04-26 21:13 UTC, Niols commented on c/testu01/stubs.c
> +value caml_bbattery_SmallCrush(value name, value bits_closure) {
Hum, OK, followed your advice and fixed that in 8a46232.

2020-04-26 21:27 UTC, Kerl13 commented on c/testu01/stubs.c
> +value caml_bbattery_SmallCrush(value name, value bits_closure) {
> As far as I know, `CAMLprim` is an old macro that is only there for compatibility purposes and can/should be omitted (actually, I think its definition is empty now).

It's indeed empty (at least from 4.02.3).
Moreover the documentation is not clear at all about it: its meaning is nowhere explained, it's sometimes present in the examples and sometimes not…

2020-04-26 21:43 UTC, Niols commented on c/testu01/stubs.c
> +}
I would like to make a binding for `unif01_CreateExternGenBits` that would make it easier to play with various definitions. If TestU01 talks about shifting by 2, I would go for that. And maybe we can add a binding like `unif01_CreateExternGenBits32` (or a better name) that takes an int32? So that the choice to give 32 bits is taken on the OCaml side and the binding remains rather neutral?

2020-04-26 21:46 UTC, Niols commented
The last few commits try to clean up and to make the GC happy. The very last one attempts to bind RepeatSmallCrush *via* Bigarray. We just want to be able to send an OCaml `int array` to a C `int[]`. The integers are always rather small. This seems like a pretty easy problem. My solution (65e4144) works but there seems to be a problem in the size of the arrays. The indices seems shifted in the following way:

| OCaml | C |
| 0 | 0 |
| 1 | 2 |
| 2 | 4 |

@Kerl13 @VLanvin any idea what I did wrong?

2020-04-26 21:47 UTC, Niols commented on c/testu01/stubs.c
> +value * caml_bits_closure = NULL;
OK, let's keep this then.

2020-04-26 21:49 UTC, Kerl13 commented on c/testu01/stubs.c
> +}
> And maybe we can add a binding like `unif01_CreateExternGenBits32` (or a better name) that takes an int32? So that the choice to give 32 bits is taken on the OCaml side and the binding remains rather neutral?

I'm in favour of this, the more control we have on the OCaml side the better it is. For the name I suggest `unif01_CreateExternGenInt32`.

2020-04-26 21:53 UTC, Kerl13 commented
> The last few commits try to clean up and to make the GC happy. The very last one attempts to bind RepeatSmallCrush _via_ Bigarray. We just want to be able to send an OCaml `int array` to a C `int[]`. The integers are always rather small. This seems like a pretty easy problem. My solution ([65e4144](https://github.com/LesBoloss-es/ocaml-rng-experiments/commit/65e41448d6af41755a7a4790fcb8d29d2d4d5d39)) works but there seems to be a problem in the size of the arrays. The indices seems shifted in the following way:
> OCaml 	C
> 0 	0
> 1 	2
> 2 	4
> 
> @Kerl13 @VLanvin any idea what I did wrong?

OCaml's `int`s are actually `long int`s on a 64bit arch. My guess would be that the cast to `int*` is wrong [here](https://github.com/LesBoloss-es/ocaml-rng-experiments/commit/65e41448d6af41755a7a4790fcb8d29d2d4d5d39#diff-5ffd7b61d5da06bd51acfd7becb38350R41). If you need a `long*` I guess you would have to make a copy.

2020-04-26 21:54 UTC, Kerl13 commented
(sorry that we didn't think of it earlier)

2020-04-26 22:58 UTC, Niols commented
The last commits provide a fix for repeated SmallCrush by carrying int32 bigarrays. They also complete the bindings with all available repeated versions. Finally, they add the FISP 140 2 test battery.

My next goal is to provide a binding for `unif01_CreateExternGenBits` (and `unif01_CreateExternGenInt32`) and change all the other bindings to use it. But this will have to wait; good night!

2020-05-02 23:01 UTC, Niols commented
Now offers an API of the form:

```ocaml
type unif01_Gen

val unif01_CreateExternGenBits : string -> (unit -> unit) -> unif01_Gen

val bbattery_SmallCrush : unif01_Gen -> unit
```

There are however issues, and most importantly a memory leak because we never destroy `unif01_Gen` objects. I guess one has to use the `finalize` field of the custom operations and bind it to the destructor for `unif01_Gen` objects.

And then, there are issues due to the fact that I really have no idea what I'm doing. In particular, I am here boxing a pointer to a C abstract thingy that itself references a function that has a Caml callback. The chances that I made the GC happy with that are extra slim.

@VLanvin Would you mind reading the last three commits?

2020-05-02 23:09 UTC, Niols commented on c/testu01/stubs.c
> +}
Now that there is a binding for `unif01_CreateExternGenBits`, and after it is read and validated, we could go back to this and implement it.

2020-05-03 09:15 UTC, Niols commented on c/testu01/stubs.c
> +}
Happy with 134d51b?

2020-05-03 17:47 UTC, Niols commented
@Kerl13 @VLanvin Does any of you know:

1. How to return a `float` value from a C `double`?

2. If there is an other way to bind global variables than with a getter and a setter? See 418f382 for the setter of `gofw_Suspectp` (the global variable in ProbDist that acts on the report of batteries in TestU01).

2020-05-03 19:35 UTC, VLanvin commented on c/testu01/stubs.c
>  }
Why is this function defined and exposed? This seems unsafe since it allows the user to manually destroy the generator, which will probably lead to an error if the generator is GC'ed later on, unless the destructor properly handles the `NULL` case. But even then, I would let the GC do the cleaning automatically.

2020-05-03 19:42 UTC, VLanvin commented
> 1. How to return a `float` value from a C `double`?

`caml_copy_double(d)` takes a double `d` and returns the corresponding `value` of type `float`.

> 2. If there is an other way to bind global variables than with a getter and a setter? See [418f382](https://github.com/LesBoloss-es/ocaml-rng-experiments/commit/418f3825fb2ea52ad0816cc3c462268a3f1bd797) for the setter of `gofw_Suspectp` (the global variable in ProbDist that acts on the report of batteries in TestU01).

I don't think so, unfortunately. The setter seems fine.

2020-05-03 20:58 UTC, Niols commented on c/testu01/stubs.c
>  }
It handles the `NULL` case correctly. I wondered quite a bit, and then decided to still expose it because:

- It is practical for consistency with the C API. It would however make sense to have at least a comment in the .mli saying that this should probably not be called.

- It is not like not exposing it would make the interface safe. Calling `CreateExternGenBits` replaces the current one with the given one.

But maybe it would still be better not to expose it?

2020-05-03 20:59 UTC, Niols commented
Thank you for this answer. I will then keep with the getters and setter. I am wondering why `caml_copy_double` isn't called `Double_val`, but nevermind, I will write the setter right away.

2020-05-03 23:06 UTC, Niols commented
Done in 57cc9e5; good night!

2020-05-04 11:08 UTC, Kerl13 commented on c/testu01/stubs.c
> +}
yep :+1:

2020-05-04 11:15 UTC, Kerl13 commented on c/testu01/bbattery_stubs.c
> +  int * a = malloc(ba32_length * sizeof(int));
I think the memory allocated here is never freed.

By the way, I thought that using bigarrays (of int32) would allow you to use them directly from C without needing to make a copy. Can't you use `ba32` directly in the *Repeat functions?

2020-05-04 12:33 UTC, Kerl13 commented on c/testu01/bbattery.ml
> +let repeat_crush gen rep = repeat_crush gen (barep rep)
There should be a check here that the array is of correct length. Otherwise it's possible to trigger invalid memory accesses by passing e.g. an empty array.

2020-05-04 12:34 UTC, Kerl13 commented on c/testu01/bbattery.ml
> +let repeat_crush gen rep = repeat_crush gen (barep rep)
(this holds for the other `repeat_*` functions as well)

2020-05-04 13:38 UTC, Niols commented on c/testu01/bbattery_stubs.c
> +  int * a = malloc(ba32_length * sizeof(int));
Oh I think you're right. The problem I have is that the C functions require an array of C int values. And I want to provide a binding that manipulate an array of OCaml values. As you've explained to me, this is actually problematic because int in C and OCaml do not have the same size. The only solution I found was to use an int32 array and have conversion on both sides. If you see an other solution for this, I will happily implement it.

2020-05-04 13:42 UTC, Niols commented on c/testu01/bbattery.ml
> +let repeat_crush gen rep = repeat_crush gen (barep rep)
I agree, but this is sadly "by design" in TestU01 and specified in the documentation so I thought I would keep it that way. A test of length of the array would require knowing the number of tests in each battery, and I don't really find a satisfying way (that is, that does not involve hardcoding the value in the bindings) of getting that number. What is your opinion on the topic?

2020-05-04 13:48 UTC, Niols commented on c/testu01/bbattery_stubs.c
> +  int * a = malloc(ba32_length * sizeof(int));
In lack of better solution wrt Bigarray, 92ad6e2 ensures the allocated array is freed.

2020-05-04 13:54 UTC, Kerl13 commented on c/testu01/bbattery_stubs.c
> +  int * a = malloc(ba32_length * sizeof(int));
I think you only have to do the conversion once. If I understand correctly, once you have a `Bigarray` of `int32` in OCaml you can access directly to its `Caml_ba_data_val(…)` field on the C side, which is already an `int32_t*` aka `int*`.

The other option was to pass an `int array` directly to C and then,on the C side, mallocating a new array of type `int*` and do the conversion: `newarray[i] = (int)Long_val(i-th field of then ocaml array)`.

Not sure if I'm being clear…

2020-05-04 13:59 UTC, Niols commented on c/testu01/bbattery_stubs.c
> +  int * a = malloc(ba32_length * sizeof(int));
For the first option, it relies on the fact that `int32_t` and `int` are the same thing in C. Is it always true? I thought the size of `int` wasn't specified in any standard?

I don't like so much the second solution, but I see how it avoids conversion on the OCaml side. And thus removes code. However, it also relies on the fact that OCaml integers are twice longer than C's ones, which depends on the platform (for OCaml's side) and on the C compiler, if I'm not mistaken.

Note that I might very well be mistaken; I'm rubbish at C.

2020-05-04 14:05 UTC, Kerl13 commented on c/testu01/bbattery.ml
> +let repeat_crush gen rep = repeat_crush gen (barep rep)
I'm very much in favour of hardcoding the numbers. Whereas it seems common practice in C to trust that the user will pass pointers to valid memory (and also because there is no notion of "length" for an `int*`), I think we should keep things "safe" on the OCaml side.

Also I doubt these numbers will ever change.

2020-05-04 14:24 UTC, Kerl13 commented on c/testu01/bbattery_stubs.c
> +  int * a = malloc(ba32_length * sizeof(int));
> I thought the size of `int` wasn't specified in any standard?

Hm, that's a good point…

Making the copy on the C side with `(int)` casts would fix this issue. But then you have to handle the memory management yourself.

Another solution is to do some introspection (for instance expose `sizeof(int)` to OCaml, note that this is different from `Nativeint.size`) in order to use the correct Bigarray type depending on the platform.

2020-05-05 13:16 UTC, Niols commented on c/testu01/bbattery.ml
> +let repeat_crush gen rep = repeat_crush gen (barep rep)
OK, I'm starting to get convinced. I tend to see bindings as a two-layer job, with one layer very low level that just mimmics the C, and then one abstraction layer (but that one is full OCaml). However, here, I don't think it can really be abstracted away as the number of tests is a value we would have to add, so I guess we can see it as part of the bindings.

2020-05-05 13:16 UTC, Niols commented
The discussion about array sizes makes me think of the following:

I agree that we would want to end with "safe" OCaml bindings. There is an other place where that plays a role and it's in the creation of an external `unif01_Gen` type. Because one could deallocate it but still have a pointer to it in OCaml. That could be solved by removing the `DeleteExternGenBits` function from the bindings. However, creating an new `unif01_Gen` actually modifies a previous one (because, behind this type, there is actually only one reference holding a generator).

A way to handle that could be to expose a new function `ModifyExternGenBits` that does not return a new OCaml value. And `CreateExternGenBits` would fail if we try to create a generator when a previous one is still existing. In that way, what is happening gets very clear. However, that feels very imperative, and we could imagine cases where we don't have a pointer to the generator, but it hasn't been reclaimed by the GC yet and we're stuck.

An other way would be to have a machinery that detects which function is being used and updates the pointer on the C side to the right function. This gives a cleaner and more OCaml-like interface, but it is probably quite complicated compared to the use case people will have.

2020-05-05 13:19 UTC, Niols commented on c/testu01/bbattery_stubs.c
> +  int * a = malloc(ba32_length * sizeof(int));
But in the first case, we still have to create a bigarray from an array on OCaml's side; and to copy it on C's side; so we still have two conversions.

I don't like the introspection so much. It is true that it would remove the copy on C's side. However, it makes the binding on OCaml's side much more involved. I am not sure it is such an improvement compared to the actual implementation (as of 92ad6e2). What do you think?

2020-05-05 13:38 UTC, Kerl13 commented on c/testu01/bbattery_stubs.c
> +  int * a = malloc(ba32_length * sizeof(int));
> But in the first case, we still have to create a bigarray from an array on OCaml's side

I don't think so. I think you can pass an OCaml array directly and do the copy like:

```C
CAMLparam1(ocamlarray);
int len = whatever;
int* newarray = malloc(sizeof(int) * len);
for (int i = 0; i < len; i++) {
  newarray[i] = Int_val(Field(ocamlarray, i));
}
```

The `Field` macro does the job of figuring out where the i-th element of the array actually is.

> I don't like the introspection so much.

Me neither…

> It is true that it would remove the copy on C's side. However, it makes the binding on OCaml's side much more involved. I am not sure it is such an improvement compared to the actual implementation (as of [92ad6e2](https://github.com/LesBoloss-es/ocaml-rng-experiments/commit/92ad6e2aeba1532bd4c2ac74fd9b4ce8fac2d804)). What do you think?

I agree with this

2020-05-05 13:49 UTC, Kerl13 commented on c/testu01/bbattery.ml
> +let repeat_crush gen rep = repeat_crush gen (barep rep)
I see your point, I like the idea the two layers.
But I tend to think that the lower level should make some sanity checks too keep the interface safe, unless there is a real interest to make unsafe functions accessible like performance critical code.

2020-05-05 13:52 UTC, Niols commented on c/testu01/bbattery_stubs.c
> +  int * a = malloc(ba32_length * sizeof(int));
> > But in the first case, we still have to create a bigarray from an array on OCaml's side
> 
> I don't think so. I think you can pass an OCaml array directly and do the copy like:
> 
> ```c
> CAMLparam1(ocamlarray);
> int len = whatever;
> int* newarray = malloc(sizeof(int) * len);
> for (int i = 0; i < len; i++) {
>   newarray[i] = Int_val(Field(ocamlarray, i));
> }
> ```
> 
> The `Field` macro does the job of figuring out where the i-th element of the array actually is.

Oooooh, very interesting. And the size can be computed with `Wosize_val`. Let me have a look. But then we still have to check the size of the array on OCaml's side. Or would you test it on C's side?

2020-05-05 14:04 UTC, Kerl13 commented on c/testu01/bbattery_stubs.c
> +  int * a = malloc(ba32_length * sizeof(int));
I guess I would make the check on the C side since we already have almost all of the machinery there. Besides you can access the macros you were referring to earlier if you do this.

I think there is a last point to discuss if we adopt this: what about the conversion from long to int from a user point of view? Should we mention in the docs that integers are truncated to fit into a platform-dependent `int`? Or should we add a check (I guess on the C side?) and raise an exception if one value is too big for `int`?

2020-05-06 14:38 UTC, Niols commented on c/testu01/stubs.c
>  }
Solved in #5. Indeed removed from the bindings.

2020-05-06 14:38 UTC, Niols commented on c/testu01/bbattery.ml
> +let repeat_crush gen rep = repeat_crush gen (barep rep)
Happy with 9b42974?

2020-05-06 15:04 UTC, Niols commented on c/testu01/bbattery_stubs.c
> +  int * a = malloc(ba32_length * sizeof(int));
Happy with b331ee4?

2020-05-06 15:05 UTC, Niols commented on c/testu01/bbattery_stubs.c
> +  int * a = malloc(ba32_length * sizeof(int));
> I think there is a last point to discuss if we adopt this: what about the conversion from long to int from a user point of view? Should we mention in the docs that integers are truncated to fit into a platform-dependent `int`? Or should we add a check (I guess on the C side?) and raise an exception if one value is too big for `int`?

I guess you mean in the conversion from an OCaml int to a C int? You're rigth that I didn't add any check. And I wasn't very happy about it. I guess we should add a check indeed, and I also guess it has to be on the C side. How, though, would you check that efficiently?

2020-05-06 15:19 UTC, Kerl13 commented on c/testu01/bbattery_stubs.c
> +  int * a = malloc(ba32_length * sizeof(int));
Yes that's what I meant.

I think I would do something like this inside the for loop:

```C
intnat x = Int_val(Field(ocamlarray, i));
if (x < 0 || (x >> (sizeof(int) - 1) != 0)
  caml_invalid_argument("Bbattery.repeat_crush");
```
It assumes that `sizeof(intnat)` (aka `Nativeint.size`) is at least `sizeof(int)` which I think is sound (but I have no proof of this claim). 

The minus one is here because we store the number into `int` and not `unsigned int`.

2020-05-06 15:19 UTC, Kerl13 commented on c/testu01/bbattery.ml
> +let repeat_crush gen rep = repeat_crush gen (barep rep)
yep!

2020-05-06 15:29 UTC, Niols commented on c/testu01/bbattery_stubs.c
> +  int * a = malloc(ba32_length * sizeof(int));
Otherwise, one could use `Long_val` and store the result in a long. Would that work?

2020-05-06 15:34 UTC, Kerl13 commented on c/testu01/bbattery_stubs.c
> +  int * a = malloc(ba32_length * sizeof(int));
Oh yes sorry, I wanted to use `Long_val`, I fear Int_val might already lose the high bits

2020-05-06 15:35 UTC, Kerl13 commented on c/testu01/bbattery_stubs.c
> +  int * a = malloc(ba32_length * sizeof(int));
And `intnat` seems to be an alias to `long` so the assumption seems legit.

2020-05-06 15:38 UTC, Niols commented
But we're certain that Long_val returns a long a than long is bigger than int, right? So why use intnat?

— Niols

Le 6 mai 2020 17:35:19 GMT+02:00, "Martin Pépin" <notifications@github.com> a écrit :
>@Kerl13 commented on this pull request.
>
>
>
>> +#define CAML_NAME_SPACE
>+#include <caml/mlvalues.h>
>+#include <caml/memory.h>
>+#include <caml/callback.h>
>+#include <caml/bigarray.h>
>+#include <caml/custom.h>
>+
>+#include <unif01.h>
>+#include <bbattery.h>
>+#include "unif01_stubs.h"
>+
>+int * int_array_from_int32_bigarray(value ba) {
>+  CAMLparam1(ba);
>+  int ba32_length = Caml_ba_array_val(ba)->dim[0];
>+  int32_t * ba32 = Caml_ba_data_val(ba);
>+  int * a = malloc(ba32_length * sizeof(int));
>
>And `intnat` seems to be an alias to `long` so the assumption seems
>legit.

2020-05-06 15:57 UTC, Kerl13 commented
Oh yes, use a `long`, you are right that this is clearer.

I wrote `intnat` because I saw the `Long_val` macro produced an `intnat` (by shifting a `value` which is an alias to `intnat`), not because I really wanted an `intnat`

2020-05-06 15:59 UTC, Kerl13 commented
They are the same anyway
And at least then fact that `Long_val` gives you a `long` is documented, so `intnat` was probably a poor choice

2020-05-06 16:00 UTC, Kerl13 commented on c/testu01/bbattery_stubs.c
> +  int * a = malloc(ba32_length * sizeof(int));
I made a mistake here, it should be `8 * sizeof(int) - 1` instead of `sizeof(int) - 1`

2020-05-06 17:00 UTC, Niols commented on c/testu01/bbattery_stubs.c
> +  int * a = malloc(ba32_length * sizeof(int));
why not

```c
unsigned long x = Long_val(Field(ocamlarray, i));
if ((x >> sizeof(int)) != 0)
  caml_invalid_argument("...");
```

I don't understand the `8 * sizeof(int) - 1`.

2020-05-06 17:17 UTC, Kerl13 commented on c/testu01/bbattery_stubs.c
> +  int * a = malloc(ba32_length * sizeof(int));
`sizeof(int)` gives you the size of `int` in number of bytes so you have to multiply by 8 to get the number of bits.

And `x` is the number of times each test should be run right? Since it is to be stored in a (signed) `int` it should fit in 31 bits, hence the minus one

2020-05-06 17:22 UTC, Kerl13 commented on c/testu01/bbattery_stubs.c
> +  int * a = malloc(ba32_length * sizeof(int));
Ok, sorry but there was a simpler way…
Apparently `limits.h` defines an `INT_MAX` macro. I guess comparing `x` with `INT_MAX` is more idiomatic than what I suggested.

2020-05-06 19:52 UTC, Niols commented on c/testu01/bbattery_stubs.c
> +  int * a = malloc(ba32_length * sizeof(int));
Sounds good! What about 6c05289?

2020-05-07 13:59 UTC, Kerl13 commented on testu01/README.md
> +Wrong. Behold: TestU01 bindings for OCaml.
Love it!

2020-05-07 14:01 UTC, Niols commented on testu01/README.md
> +Wrong. Behold: TestU01 bindings for OCaml.
Documentation; very important.

2020-05-07 14:06 UTC, Niols commented on testu01/README.md
> +  let rep = Array.make 97 0 in
Use `Testu01.Bbattery.ntests_crush`. Also, maybe open Testu01?

2020-05-07 14:07 UTC, Niols commented on testu01/README.md
> +suspicious (that is, inferior to `suspectp` or bigger than `1 - suspectp`), but
suspect = inferior to suspectp or bigger than 1 - suspectp **and** not eps or 1 - eps.

2020-05-07 14:08 UTC, Niols commented on testu01/README.md
> +bits`, sets (that is optional, the default is `0.001`) the threshold for suspect
putting the parenthesis later in the sentence makes more sense

2020-05-07 14:08 UTC, Niols commented on testu01/README.md
> +void bbattery_RepeatBigCrush(unif01_Gen* gen, int[] rep);
I'm having a doubt if `int[]` is indeed valid C in a signature?

2020-05-07 14:09 UTC, Niols commented on testu01/README.md
> +    returns an `int32`.
Maybe add that it should be seen as unsigned and all bits must be provided. And that, in particular, `fun () -> Random.int32 Int32.max_int` is a bad function here because the highest bit is always 0.

2020-05-07 14:09 UTC, Niols commented on testu01/README.md
> +- for Archlinux: `testu01`, in AUR.
Instructions about manual compilation? Link to the website?

2020-05-07 14:17 UTC, Niols commented on testu01/README.md
> +val Probdist.Gofw.set_suspectp : float -> unit
Actually, right now, we have two toplevel modules: Testu01 and Probdist. We could possibly have a third one later, Mylib (yes, great name…). 

1. The two libraries are toplevel modules: `Testu01` and `Probdist`. If we have bindings from "mylib" (great name) one day, this would be a third toplevel module `Mylib`. This is the solution implemented at the moment.

2. We could put everything under a main module named after the lib: `Testu01.Testu01`, `Testu01.Probdist`, and possibly `Testu01.Mylib`.

3. Something intermediary to avoid having `Testu01.Testu01`. The two others would still be submodules of it.

4. `testu01` and `probdist` could be really two different (like OPAM) libraries, with `testu01` depending on `probdist`. I don't think it makes so much sense. Especially considering that we don't bind much from Probdist, it is mostly just a dependency of the C version of TestU01.

@Kerl13 An opinion?

2020-05-07 14:18 UTC, Niols commented on testu01/testu01/bbattery.ml
> +external small_crush : Unif01.gen -> unit =
@Kerl13 Should I add .mli files for all this? I guess it would be cleaner, but there is already TestU01's documentation, we're just bindings…

2020-05-07 14:19 UTC, Niols commented on testu01/testu01/bbattery.ml
> +external small_crush : Unif01.gen -> unit =
And I'm lazy, I guess.

2020-05-07 14:19 UTC, Niols commented on testu01/testu01/bbattery_stubs.c
> +  return caml_bbattery_RepeatBlockAlphabit(argv[0], argv[1], argv[2], argv[3], argv[4], argv[5]);
@VLanvin Do you know if CAMLparam and CAMLreturn are still necessary in that case?

2020-05-07 14:21 UTC, Niols commented on testu01/testu01/bbattery_stubs.c
> +  unif01_Gen *gen = unif01_Gen_unbox(bgen);
Err, here, `gen` is just a pointer to the data part of the boxed unif01_Gen. Do we need to free this afterwards? Or would that free the whole data part? @Kerl13 @VLanvin

2020-05-07 14:21 UTC, Niols commented on testu01/testu01/bbattery_stubs.c
> +  bbattery_AlphabitFile (Bytes_val(filename), Double_val(nb));
Do we trust `Bytes_val` or should we copy the string?

2020-05-07 14:22 UTC, Niols commented on testu01/testu01/bbattery_stubs.c
> +  bbattery_AlphabitFile (Bytes_val(filename), Double_val(nb));
The copy could be done on OCaml's side if we're lazy here.

2020-05-07 14:22 UTC, Kerl13 requested changes
Looks good, just a few remaining remarks and I'm ready to merge

2020-05-07 14:22 UTC, Kerl13 commented on testu01/testu01/unif01_stubs.c
> +  memcpy(Data_custom_val(bgen), &gen, sizeof(unif01_Gen*));
I think no `memcpy` is not necessary here: 

```C
Data_custom_val(bgen) = gen;
```
should be fine

2020-05-07 14:22 UTC, Kerl13 commented on testu01/testu01/unif01_stubs.c
> +  return Int_val(caml_callback((value) bits, Val_unit)) << 2;
Maybe cast this to `unsigned int` before shifting.
Otherwise this may trigger signed integers overflows which have undefined behaviours

2020-05-07 14:22 UTC, Kerl13 commented on testu01/testu01/unif01_stubs.c
> +#define IGNORE(x) (void)(x)
note to myself: this should probably be in the header file

2020-05-07 14:23 UTC, Niols commented on testu01/testu01/swrite_stubs.c
> +  CAMLreturn((swrite_Basic == TRUE) ? Val_true : Val_false);
I didn't look into it, but maybe `TRUE` and `FALSE` are just macros for `0` and `1`? Can we have a more direct conversion?

2020-05-07 14:24 UTC, Niols commented on testu01/testu01/unif01_stubs.c
> +static void WrExternGen (void * junk) { IGNORE(junk); }
Out of curiosity, what does `IGNORE` do? I guess it's to make some compiler warnings happy?

2020-05-07 14:48 UTC, Kerl13 commented on c/testu01/bbattery_stubs.c
> +  int * a = malloc(ba32_length * sizeof(int));
:+1:

2020-05-07 15:29 UTC, Kerl13 commented on testu01/README.md
> +void bbattery_RepeatBigCrush(unif01_Gen* gen, int[] rep);
Yes it is, but my rough understanding is that since you will get a pointer anyway (the array is passed by reference) and since `int[]` does not add information about the size of the array, `int*` makes more sense. But I could clearly be missing something

2020-05-07 15:31 UTC, Kerl13 commented on testu01/README.md
> +    returns an `int32`.
Yes, I think it's worth explaining this

2020-05-07 15:32 UTC, Kerl13 commented on testu01/README.md
> +- for Archlinux: `testu01`, in AUR.
Just a link?

2020-05-07 15:35 UTC, Kerl13 commented on testu01/README.md
> +val Probdist.Gofw.set_suspectp : float -> unit
I'd say 1. is totally fine at the moment but I prefer 2 and 3 (I have no particular preference between the two but I'm curious how you would do 3.)
I'm definitely not in favour of 4

2020-05-07 15:40 UTC, Kerl13 commented on testu01/testu01/bbattery.ml
> +external small_crush : Unif01.gen -> unit =
Go for the lazy option then ;)
This is just for us to play around at the moment, it doesn't have to be as polished and well-documented as an opam release. I guess we'll come back to this when (if) we do a release

2020-05-07 15:46 UTC, Kerl13 commented on testu01/testu01/bbattery_stubs.c
> +  unif01_Gen *gen = unif01_Gen_unbox(bgen);
No, `gen` is statically allocated on the stack and is poped at the end of the function call. The only things you have to `free` are those you have `malloc`ed (in this case the `unif01_Gen` struct and its content, which you do in the finalizer).

2020-05-07 15:55 UTC, Kerl13 commented on testu01/testu01/bbattery_stubs.c
> +  bbattery_AlphabitFile (Bytes_val(filename), Double_val(nb));
I'm not sure I understand the question.

If you refer to the fact that `Bytes_val` gives an `unsigned char *` and that `bbattery_AlphabitFile` expects a `char*`, I guess this is fine but I'm not sure…

Another question is: do we trust than `bbattery_AlphabitFile` will not modify the string? I guess so, but that would have been cleaner from Testu01 to add a `const` here.

Bref, I'd say leave it like this unless there is something else I didn't see

2020-05-07 15:56 UTC, Kerl13 commented on testu01/testu01/swrite_stubs.c
> +  CAMLreturn((swrite_Basic == TRUE) ? Val_true : Val_false);
It is probably the case but it feels cleaner to me as it is right now.

2020-05-07 16:00 UTC, Kerl13 commented on testu01/testu01/unif01_stubs.c
> +static void WrExternGen (void * junk) { IGNORE(junk); }
Exactly. Casting to `void` seems to be the idiomatic way to say "I don't case about this" to the compiler, so I did this to mimic OCaml's `ignore` function

2020-05-07 21:13 UTC, Niols commented on testu01/README.md
> +void bbattery_RepeatBigCrush(unif01_Gen* gen, int[] rep);
Thanks; I'll put `int*`.

2020-05-07 21:18 UTC, Niols commented on testu01/README.md
> +val Probdist.Gofw.set_suspectp : float -> unit
For 3., I would just have in `testu01.ml`:

```ocaml
module Probdist = Probdist
module Mylib = Mylib
module Unif01 = Unif01
module Bbattery = Bbattery
```

the two former being the other two libs and the two latter being modules of TestU01. Maybe 2. would make more sense? But `Testu01.Testu01`...

2020-05-07 21:19 UTC, Niols commented on testu01/testu01/bbattery.ml
> +external small_crush : Unif01.gen -> unit =
:+1:

2020-05-07 21:19 UTC, Niols commented on testu01/testu01/bbattery_stubs.c
> +  unif01_Gen *gen = unif01_Gen_unbox(bgen);
Nice. So all good with respect to that.

2020-05-07 21:22 UTC, Niols commented on testu01/testu01/bbattery_stubs.c
> +  bbattery_AlphabitFile (Bytes_val(filename), Double_val(nb));
My question was your "another question". Using `String_val` does not work as it types the string as a `const char*` which cannot then be given to the batteries. For safety, one would have to copy the string either on OCaml's side (`Bytes.of_string`) or on C's side.

2020-05-07 21:27 UTC, Niols commented on testu01/testu01/unif01_stubs.c
> +  memcpy(Data_custom_val(bgen), &gen, sizeof(unif01_Gen*));
Nah, `Data_custom_val` is defined with:

```c
#define Data_custom_val(v) ((void *) &Field((v), 1))
```

and that wouldn't be valid on the left of an `=`.

2020-05-07 21:27 UTC, Niols commented on testu01/testu01/unif01_stubs.c
> +  return Int_val(caml_callback((value) bits, Val_unit)) << 2;
Done.

2020-05-07 21:28 UTC, Niols commented on testu01/testu01/unif01_stubs.c
> +#define IGNORE(x) (void)(x)
I think you did it since then?

2020-05-07 21:28 UTC, Niols commented on testu01/testu01/swrite_stubs.c
> +  CAMLreturn((swrite_Basic == TRUE) ? Val_true : Val_false);
Fine by me!

2020-05-07 21:28 UTC, Niols commented on testu01/testu01/unif01_stubs.c
> +static void WrExternGen (void * junk) { IGNORE(junk); }
Thanks :-)

2020-05-07 21:46 UTC, Kerl13 commented on testu01/testu01/bbattery_stubs.c
> +  bbattery_AlphabitFile (Bytes_val(filename), Double_val(nb));
TestU01's code does not seem to modify this string and I see no reason why it would.
I guess the reason they did not write `const` is just "bad" habits? I'm in favour of "trusting" Testu01 to leave the string unmodified.

2020-05-07 21:46 UTC, Kerl13 commented on testu01/testu01/bbattery_stubs.c
> +  bbattery_AlphabitFile (Bytes_val(filename), Double_val(nb));
But if you feel more like making a copy go for it, that's fine too!

2020-05-07 21:49 UTC, Niols commented on testu01/testu01/bbattery_stubs.c
> +  return caml_bbattery_RepeatBlockAlphabit(argv[0], argv[1], argv[2], argv[3], argv[4], argv[5]);
Three more questions:

- How would you use CAMLparam* when what we have here is an array of values?
- What is the purpose of CAMLparam0? When should it be used?
- Should we use CAMLreturn when the returned value is not of type `value`? When should we do that?

2020-05-07 21:50 UTC, Niols commented on testu01/testu01/bbattery_stubs.c
> +  bbattery_AlphabitFile (Bytes_val(filename), Double_val(nb));
laaaazyyyyyyyyy!

2020-05-07 21:51 UTC, Kerl13 commented on testu01/testu01/unif01_stubs.c
> +#define IGNORE(x) (void)(x)
yep

2020-05-07 21:51 UTC, Kerl13 commented on testu01/testu01/unif01_stubs.c
> +  memcpy(Data_custom_val(bgen), &gen, sizeof(unif01_Gen*));
sorry, got confused

2020-05-07 21:52 UTC, Niols commented on testu01/testu01/unif01_stubs.c
> +  memcpy(Data_custom_val(bgen), &gen, sizeof(unif01_Gen*));
Nah, it's fine, it made me read this macro I was using ;-)

2020-05-07 22:28 UTC, Kerl13 commented on testu01/README.md
> +val Probdist.Gofw.set_suspectp : float -> unit
Interesting, so if dune finds a file named like the library it uses it as the entrypoint of the lib?

> But `Testu01.Testu01`…

Yes, that's sub-optimal

2020-05-07 22:33 UTC, Niols commented on testu01/README.md
> +val Probdist.Gofw.set_suspectp : float -> unit
> Interesting, so if dune finds a file named like the library it uses it as the entrypoint of the lib?

Yes, and it can be any file. But in that case, you have to include all the other modules by hand with `module Foo = Foo`. Or possibly `include Foo`. Or `module Foo = Make(...)`. etc. Very practical.

2020-05-07 23:17 UTC, merged